---
- hosts: onadata
  gather_facts: False
  serial: 1 # Runs playbook one server at at time (to achieve a rolling update)
  max_fail_percentage: 0
  pre_tasks:
    - include_tasks: tasks/python3-ubuntu.yml
    - name: Setup Ansible
      setup:
    - name: Install acl
      become: true
      shell: apt install acl
  roles:
    - role: onaio.pgbouncer
      become: true
      tags:
        - pgbouncer
    - role: onaio.onadata
      become: true
      tags:
        - onadata
    - role: onaio.systemd_cifs_mount
      become: true
      tags:
        - cifs
    - role: onaio.nginx
      become: true
      nginx: "nginx=1.26.*"
      tags:
        - nginx
    - role: onaio.monit
      become: true
      tags:
        - nginx
    - role: onaio.collectd
      collectd_deployed_app_name: "onadata"
      collectd_deployed_app_version: "{{ onadata_version }}"
      collectd_scripts: ["nginx"]
      become: true
      tags:
        - collectd
      when: install_collectd
    - role: onaio.logstash
      become: true
      tags:
       - logstash
      when: install_logstash
