---
- hosts: rabbitmq
  gather_facts: False
  pre_tasks:
    - include_tasks: tasks/python3-ubuntu.yml
    - name: Setup Ansible
      setup:
  post_tasks:
    - name: Verify that rabbitmq user is created as expected
      become: true
      shell: rabbitmqctl authenticate_user {{ rabbitmq_admin_user }} {{ rabbitmq_admin_password }}
  roles:
    - role: onaio.rabbitmq
      become: true
      tags:
        - rabbitmq
    - role: onaio.monit
      become: true
      tags:
        - monit
    - role: onaio.collectd
      collectd_deployed_app_name: "rabbitmq"
      collectd_deployed_app_version: "latest"
      become: true
      tags:
        - collectd
      when: install_collectd
