---
- hosts: rabbitmq
  gather_facts: False
  pre_tasks:
    - include_tasks: tasks/python3-ubuntu.yml
    - name: Setup Ansible
      setup:
  roles:
    - role: kbrebanov.erlang
      become: true
      tags:
        - erlang
    - role: onaio.rabbitmq
      become: true
      tags:
        - rabbitmq
    - role: onaio.monit
      become: true
      tags:
        - monit
    - role: onaio.collectd
      collectd_deployed_app_name: "rabbitmq"
      collectd_deployed_app_version: "latest"
      become: true
      tags:
        - collectd
      when: install_collectd
