---
- name: Install the custom template # noqa 301
  become: true
  become_user: "{{ onadata_system_user }}"
  shell: "(git remote add template {{ onadata_custom_template_git_url }} || true) && git fetch template {{ onadata_custom_template_version }} && git reset HEAD onadata/libs/custom_template && rm -rf onadata/libs/custom_template && git read-tree --prefix=onadata/libs/custom_template -u template/{{ onadata_custom_template_version }}" # noqa 204
  args:
    executable: /bin/bash
    chdir: "{{ onadata_checkout_path }}"
  when: onadata_enable_custom_templates

- name: Install tableau library
  become: true
  become_user: "{{ onadata_system_user }}"
  pip:
    name: "git+https://github.com/onaio/ona-tableau-connector.git#egg=onadata-connector"
    virtualenv: "{{ onadata_venv_path }}"
  when: onadata_include_tableau

- name: Delete git key
  file:
    state: absent
    path: "{{ onadata_system_user_home }}/.ssh/{{ onadata_git_key_filename }}"
  become: true
  become_user: "{{ onadata_system_user }}"
  when:
    - not onadata_unmanaged_git_key

- name: Generate Docs
  become: true
  become_user: "{{ onadata_system_user }}"
  shell: "source {{ onadata_venv_path }}/bin/activate && /usr/bin/make html"
  args:
    executable: /bin/bash
    chdir: "{{ onadata_codebase_path }}/docs"
