---
- name: Install extras
  include_tasks: install.yml
  tags:
    - install

- name: Initialize the Django app
  include_tasks: init.yml
  when: onadata_run_init_commands
  tags:
    - init

- name: Change EMQX cert and key file ownership
  include_tasks: chown-emqtt-certs.yaml
