---
ansible_python_interpreter: "/usr/bin/env python3"

example_postgresql_host: "10.0.0.5"
example_ancillary_host: "10.0.0.2"
example_api_host_0: "10.0.0.3"
example_api_host_1: "10.0.0.4"

example_postgresql_ssh_host: "{{ example_postgresql_host }}"
example_ancillary_ssh_host: "{{ example_ancillary_host }}"
example_api_ssh_host_0: "{{ example_api_host_0 }}"
example_api_ssh_host_1: "{{ example_api_host_1 }}"

set_hostname: true
server_hostname: "{{ inventory_hostname }}"

install_collectd: true
collectd_scripts_initial:
  - "graphite"
  - "cpu"
  - "disk"
  - "load"
  - "memory"
collectd_graphite_server_ip: "127.0.0.1"
collectd_graphite_server_port: 2003
collectd_graphite_server_protocol: "tcp"
collectd_server_type: "production"
collectd_server_owner: "example-org"

postgresql_onadata_db: "onadata"
postgresql_onadata_user: "onadata"
postgresql_onadata_password: "somesecret"

rabbitmq_admin_user: "admin"
rabbitmq_admin_password: "somesecret"
rabbitmq_port: 5672
rabbitmq_management_port: 15672

# Remove the "email" and "email_smtp" items from the monit_scripts
# list in the group and host vars if you don't want to configure
# email notifications
monit_email_admins: [{"Admin", "admin@example.com"}]
no_reply_monit_email: "no-reply@example.com"
# Remove the "email_smtp" item from the monit_scripts list in the
# group and host vars if you don't need to configure SMTP to send
# email notifications
monit_smtp_server: "127.0.0.1"
monit_smtp_port: "25"
monit_smtp_username: "root"
monit_smtp_password: ""
monit_setup_mode: true
monit_version: "1:5.*"
slack_monit_endpoint: ""
