---
- name: Converge
  hosts: all
  tasks:
    - import_role:
        name: ansible-onadata
      vars:
        onadata_run_init_commands: false
        onadata_enable_celery: true
        onadata_manage_services: true
        onadata_celeryd_extra_env_vars:
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
