---
- name: Verify
  hosts: all
  tasks:
    - name: Populate host_file.
      stat:
        path: "/etc/hosts"
      register: host_file

    - name: Fail if host file does not exist
      fail:
      when: not host_file.stat.exists

    - name: Check that host file belongs to root group
      fail:
      when: not host_file.stat.gr_name == "root"

    - name: Check that host file belongs to root user
      fail:
      when: not host_file.stat.pw_name == "root"

    - name: Populate service facts
      service_facts:

    - name: Check that celeryd service exists
      fail:
      when: not ansible_facts.services["celeryd-onadata.service"]

    - name: Check that celerybeat service exists
      fail:
      when: not ansible_facts.services["celerybeat-onadata.service"]

    - name: Check that onadata service exists
      fail:
      when: not ansible_facts.services["onadata.service"]
