---
rabbitmq_user: "{{ rabbitmq_admin_user }}"
rabbitmq_ulimit_open_files: 512
rabbitmq_users:
  - user: "{{ rabbitmq_admin_user }}"
    password: "{{ rabbitmq_admin_password }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    tags: administrator
rabbitmq_plugins:
  - rabbitmq_management
  - rabbitmq_top
